chore: node23 test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,7 +10,8 @@ on:
 
 jobs:
   basic_node_test:
-    name: 'Tests on ${{matrix.os}} with node${{matrix.node}}'
+    name: 'Basic tests on ${{matrix.os}} with node${{matrix.node}}'
+    needs: early_testing_for_node23
     strategy:
       matrix:
         os: [ubuntu-latest]
@@ -30,8 +31,8 @@ jobs:
      - name: Run unit test
        run: npm run test
 
-  platform_spec_test:
-    name: 'Tests on ${{matrix.os}} with node${{matrix.node}}'
+  windows_and_macos_test:
+    name: 'Platform tests on ${{matrix.os}} with node${{matrix.node}}'
     needs: basic_node_test
     strategy:
       matrix:
@@ -57,8 +58,8 @@ jobs:
      - name: Run unit test
        run: npm run test
 
-  fast_node_test:
-    name: 'Tests on ${{matrix.os}} with node${{matrix.node}}'
+  historical_versions_node_test:
+    name: 'Historical versions of node${{matrix.node}} test'
     needs: basic_node_test
     strategy:
       matrix:
@@ -78,3 +79,29 @@ jobs:
        run: npx playwright install chromium
      - name: Run unit test
        run: npm run test
+
+  early_testing_for_node23:
+    name: 'Early testing for node23'
+    runs-on: ubuntu-latest
+    steps:
+     - uses: actions/checkout@v2
+     - uses: actions/setup-node@v2
+       with:
+         node-version: 23
+     - name: Install npm dependencies
+       run: npm install
+     - name: Print put node & npm version
+       run: node --version && npm --version 
+     - name: Install chromium
+       run: npx playwright install chromium
+     - name: Run unit test
+       run: |
+          status=0
+          npm run test || status=$?
+          if [ ${status} -ne 0 ]; then
+            echo "::warning:: Early testing for node23 job failed."
+            echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
+            echo "optional_fail_status=${status}" >> "${GITHUB_OUTPUT}"
+            exit 0  # Ignore error here to keep the green checkmark going
+          fi;
+          exit ${status}
